---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Terminal
    path: /wetty
    port: 443
  - name: Gitea
    url: 'https://gitea.${DOMAIN}'
